- hosts: localhost

  tasks:

     - name: setting up security/firewall group
       ec2_group:
          name: Senica_AWS_Security_Group
          description: rules to allow traffic on port 22 and 80
          region: eu-west-1
          rules
           - proto: tcp
             from_port: 80
             to_port: 80
             cidr_ip: 0.0.0.0/0
           - proto: tcp
             from_port: 22
             to_port: 22
             cidr_ip: 0.0.0.0/0
          rules_egress:
           - proto: all
             cidr_ip: 0.0.0.0/0

     - name: provision an ec2 instance
       ec2:
          key name: senica-AWSkey
          region: eu-west-1
          instance_type: t2.micro
          image:ami-94b236ed
          wait: yes
          wait timeout: 500
          count: 1
          instance_tags:
            name:awstestserver
            owner: senica
          monitoring: no
          vpc_subnet_id: subnet-4934ef2f
          assign_public_ip: yes
          group: Senica_AWS_Security_Group
       register: ec2_out

     - name: wait for ssh to start
       wait_for: host={{ item.public_dns_name }} port:22 delay=60 timeout=320 state=restarted
       with_items: '{{ec2_out.instances}}'
